---
all:
  children:
    nameservers:
      hosts:
        dhcp1.cnv.massopen.cloud:
          ansible_host: "cnv-dhcp1.massopen.cloud"
          public_ip: "129.10.5.55/24"
          baremetal_ip: "192.12.185.101/24"
          ipmi_ip: "10.0.0.50/19"
          baremetal_mac: "56:6f:59:6b:00:92"
        dhcp2.cnv.massopen.cloud:
          ansible_host: "cnv-dhcp2.massopen.cloud"
          public_ip: "129.10.5.56/24"
          baremetal_ip: "192.12.185.102/24"
          ipmi_ip: "10.0.0.51/19"
          baremetal_mac: "56:6f:59:6b:00:93"
      vars:
        ansible_user: root
        pxe: true
        authorized_key_url:
          - https://github.com/larsks.keys
