---
# Configure nameservers with appropriate networking, dnsmasq, etc.
- hosts: nameservers
  become: true
  roles:
    - role: networking
      tags: [networking]

    - role: dnsmasq
      tags: [dnsmasq]
