---
# Configure nameservers with appropriate networking, dnsmasq, etc.
- hosts: nameservers
  become: true
  roles:
    - nameserver

# Generate per-host pxelinux configuration based on values from
# inventory. This targets the pxe_clients group, which is dynamic
# group created by using the "constructed" inventory plugin from hosts
# that have the "pxe" fact set to true in their inventory entry.
- hosts: pxe_clients
  gather_facts: false
  tags: [kickstart]
  tasks:
    - import_role:
        name: nameserver
        tasks_from: pxeconfig
