---
# Configure nameservers with appropriate networking, dnsmasq, etc.
- hosts: nameservers
  become: true
  roles:
    - role: authorized_keys
      tags: [ssh]

    - role: networking
      tags: [networking]

    - role: dnsmasq
      tags: [dnsmasq]

    - role: bootserver
      tags: [bootserver]
