---
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: reload networkmanager
  shell: |
    nmcli c reload
    nmcli -g name c show | while read name; do
      nmcli c down $name; nmcli c up $name
    done
