---
- name: install selinux policy module
  copy:
    src: local.pp
    dest: /root/local.pp

- name: activate selinux policy module
  command: >-
    semodule -i /root/local.pp

- name: create tftpboot directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /srv/tftpboot
    - /srv/tftpboot/pxelinux
    - /srv/tftpboot/pxelinux/pxelinux.cfg
    - /srv/tftpboot/uefi
    - /srv/tftpboot/images
    - /srv/tftpboot/images/centos8
    - /srv/tftpboot/ks

- name: create images symlink
  file:
    path: /srv/tftpboot/pxelinux/images
    state: link
    src: /srv/tftpboot/images

- name: install apache configuration
  template:
    src: "{{ item }}"
    dest: "/etc/httpd/conf.d/{{ item.replace('apache-', '') }}"
  loop:
    - apache-tftpboot.conf
    - apache-media.conf
  notify: restart httpd

- name: install centos kickstart configuration
  tags: [kickstart]
  template:
    src: ks.cfg
    dest: /srv/tftpboot/ks/centos-ks.cfg
  vars:
    repo_url: "http://mirrors.mit.edu/centos/8-stream/BaseOS/x86_64/os"

- name: install rhel kickstart configuration
  tags: [kickstart]
  template:
    src: ks.cfg
    dest: /srv/tftpboot/ks/rhel-ks.cfg
  vars:
    repo_url: "http://{{ baremetal_ip|ipv4('address') }}/media/"

- name: activate httpd
  service:
    name: httpd
    state: started
    enabled: true

- name: download kernel and initrd
  tags: [download]
  get_url:
    url: "{{ item }}"
    dest: /srv/tftpboot/images/centos8
  loop:
    - "{{ centos_8_kernel_url }}"
    - "{{ centos_8_initrd_url }}"

- name: copy pxelinux to tftpboot directory
  command: >-
    cp /tftpboot/{{ item }} /srv/tftpboot/pxelinux
  loop:
    - ldlinux.c32
    - libcom32.c32
    - libutil.c32
    - pxelinux.0
    - vesamenu.c32
  args:
    creates: "/srv/tftpboot/pxelinux/{{ item }}"

- name: copy uefi shim to tftpboot directory
  command: >-
    cp /boot/efi/EFI/centos/shimx64.efi /srv/tftpboot/uefi
  args:
    creates: /srv/tftpboot/uefi/shimx64.efi

- name: copy grub to tftpboot directory
  command: >-
    cp /boot/efi/EFI/centos/grubx64.efi /srv/tftpboot/uefi
  args:
    creates: /srv/tftpboot/uefi/grubx64.efi

- name: create selinux contexts
  tags: [selinux]
  sefcontext:
    target: "{{ item }}"
    setype: tftpdir_t
    state: present
  loop:
    - /srv/tftpboot
    - /srv/tftpboot/.*

- name: restore selinux contexts
  tags: [selinux]
  command: >-
    restorecon -irv /srv/tftpboot

