---
- name: configure public interface
  tags: [net.public]
  template:
    src: ifcfg.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-public
  vars:
    iface:
      bootproto: none
      name: public
      device: ens10
      cidr: "{{ public_ip }}"
      gateway: "{{ public_ip | nthhost(1) }}"
      dns:
        - 8.8.8.8
        - 8.8.4.4
      domain: "{{ os_base_domain }}"
  notify:
    - reload networkmanager

- name: configure ipmi interface
  tags: [net.ipmi]
  template:
    src: ifcfg.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-ipmi
  vars:
    iface:
      bootproto: none
      name: ipmi
      device: ens9
      cidr: "{{ ipmi_ip }}"
  notify:
    - reload networkmanager

- name: configure baremetal interface
  tags: [net.baremetal]
  template:
    src: ifcfg.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-baremetal
  vars:
    iface:
      bootproto: none
      name: baremetal
      device: ens3
      cidr: "{{ baremetal_ip }}"
  notify:
    - reload networkmanager
