---
- name: general system configuration
  tags: [system]
  import_tasks: system.yml

- name: general network configuration
  tags: [net]
  import_tasks: network.yml

- name: configure network interfaces
  tags: [net]
  import_tasks: interfaces.yml

- name: configure network booting
  tags: [boot]
  import_tasks: bootserver.yml

- name: configure dnsmasq
  tags: [dnsmasq]
  import_tasks: dnsmasq.yml
