---
- name: set dns_servers variable
  set_fact:
    dns_servers: "{{ dns_servers + [ hostvars[item].baremetal_ip | ipv4('address') ] }}"
  loop: "{{ groups.nameservers }}"
  vars:
    dns_servers: []

- name: create dnsmasq configuration
  template:
    src: dnsmasq.j2.conf
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq

- name: activate dnsmasq service
  service:
    name: dnsmasq
    state: started
    enabled: true
