---
- name: enable ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true

- name: move ipmi interface to internal zone
  tags: [net.firewall]
  firewalld:
    zone: internal
    interface: ens9
    permanent: true
    immediate: true
    state: enabled

- name: enable masquerade on internal zone
  tags: [net.firewall]
  firewalld:
    zone: internal
    masquerade: true
    permanent: true
    immediate: true
    state: enabled

- name: open up firewall
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - dhcp
    - dns
    - tftp
    - http
