---
- name: set pxelinux filename
  set_fact:
    pxelinux_filename: "01-{{ baremetal_mac.lower().replace(':', '-') }}"

- delegate_to: "{{ nameserver_host }}"
  template:
    src: pxelinux.j2.cfg
    dest: "/srv/tftpboot/pxelinux/pxelinux.cfg/{{ pxelinux_filename }}"
  loop: "{{ groups.nameservers }}"
  loop_control:
    loop_var: nameserver_host
